"""initial schema

Revision ID: e4a7aeea118b
Revises:
Create Date: 2026-04-18 11:21:17.787713

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e4a7aeea118b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_name", sa.Text(), nullable=False),
        sa.Column("trace_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ts", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("tier", sa.Text(), nullable=True),
        sa.Column("sla_days", sa.Integer(), nullable=True),
        sa.Column("contact_email", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "disruptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("lat", sa.Numeric(), nullable=True),
        sa.Column("lng", sa.Numeric(), nullable=True),
        sa.Column("radius_km", sa.Numeric(), nullable=True),
        sa.Column("source_signal_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ports",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("lat", sa.Numeric(), nullable=True),
        sa.Column("lng", sa.Numeric(), nullable=True),
        sa.Column("modes", sa.ARRAY(sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_category", sa.Text(), nullable=False),
        sa.Column("source_name", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("lat", sa.Numeric(), nullable=True),
        sa.Column("lng", sa.Numeric(), nullable=True),
        sa.Column("radius_km", sa.Numeric(), nullable=True),
        sa.Column("source_urls", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("dedupe_hash", sa.Text(), nullable=False),
        sa.Column("promoted_to_disruption_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_hash"),
    )
    op.create_table(
        "skus",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("family", sa.Text(), nullable=True),
        sa.Column("industry", sa.Text(), nullable=True),
        sa.Column("unit_cost", sa.Numeric(), nullable=True),
        sa.Column("unit_revenue", sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("tier", sa.Integer(), nullable=True),
        sa.Column("industry", sa.Text(), nullable=True),
        sa.Column("reliability_score", sa.Numeric(), nullable=True),
        sa.Column("categories", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("lat", sa.Numeric(), nullable=True),
        sa.Column("lng", sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "impact_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("disruption_id", sa.UUID(), nullable=False),
        sa.Column("total_exposure", sa.Numeric(), nullable=False),
        sa.Column("units_at_risk", sa.Integer(), nullable=False),
        sa.Column("cascade_depth", sa.Integer(), nullable=False),
        sa.Column("sql_executed", sa.Text(), nullable=True),
        sa.Column("reasoning_trace", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["disruption_id"],
            ["disruptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("customer_id", sa.Text(), nullable=False),
        sa.Column("sku_id", sa.Text(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("revenue", sa.Numeric(), nullable=False),
        sa.Column("sla_breach_penalty", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mitigation_options",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("impact_report_id", sa.UUID(), nullable=False),
        sa.Column("option_type", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("delta_cost", sa.Numeric(), nullable=False),
        sa.Column("delta_days", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["impact_report_id"],
            ["impact_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipments",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("po_id", sa.Text(), nullable=False),
        sa.Column("supplier_id", sa.Text(), nullable=False),
        sa.Column("origin_port_id", sa.Text(), nullable=False),
        sa.Column("dest_port_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=True),
        sa.Column("eta", sa.Date(), nullable=True),
        sa.Column("value", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dest_port_id"],
            ["ports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_port_id"],
            ["ports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["po_id"],
            ["purchase_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "affected_shipments",
        sa.Column("impact_report_id", sa.UUID(), nullable=False),
        sa.Column("shipment_id", sa.Text(), nullable=False),
        sa.Column("exposure", sa.Numeric(), nullable=False),
        sa.Column("days_to_sla_breach", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["impact_report_id"],
            ["impact_reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
        ),
        sa.PrimaryKeyConstraint("impact_report_id", "shipment_id"),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mitigation_id", sa.UUID(), nullable=False),
        sa.Column("approved_by", sa.Text(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("state_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["mitigation_id"],
            ["mitigation_options.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "draft_communications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mitigation_id", sa.UUID(), nullable=False),
        sa.Column("recipient_type", sa.Text(), nullable=False),
        sa.Column("recipient_contact", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mitigation_id"],
            ["mitigation_options.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Manual indexes from plan §8.1
    op.create_index("idx_signals_first_seen", "signals", [sa.text("first_seen_at DESC")])
    op.create_index("idx_disruptions_status", "disruptions", ["status"])
    op.create_index("idx_shipments_status", "shipments", ["status"])
    op.create_index("idx_shipments_origin", "shipments", ["origin_port_id"])
    op.create_index("idx_agent_log_trace", "agent_log", ["trace_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop manual indexes before tables
    op.drop_index("idx_agent_log_trace", table_name="agent_log")
    op.drop_index("idx_shipments_origin", table_name="shipments")
    op.drop_index("idx_shipments_status", table_name="shipments")
    op.drop_index("idx_disruptions_status", table_name="disruptions")
    op.drop_index("idx_signals_first_seen", table_name="signals")
    op.drop_table("draft_communications")
    op.drop_table("approvals")
    op.drop_table("affected_shipments")
    op.drop_table("shipments")
    op.drop_table("mitigation_options")
    op.drop_table("purchase_orders")
    op.drop_table("impact_reports")
    op.drop_table("suppliers")
    op.drop_table("skus")
    op.drop_table("signals")
    op.drop_table("ports")
    op.drop_table("disruptions")
    op.drop_table("customers")
    op.drop_table("agent_log")
    # ### end Alembic commands ###
